env:
   browser: true
   es2021: true
extends:
   - eslint:recommended
   - plugin:react/recommended
   - plugin:react/jsx-runtime
   - plugin:react-hooks/recommended
   - plugin:@typescript-eslint/recommended
   - prettier
parser: '@typescript-eslint/parser'
parserOptions:
   ecmaFeatures:
      jsx: true
   ecmaVersion: latest
   sourceType: module
plugins:
   - react
   - react-hooks
   - '@typescript-eslint'
overrides:
   - files:
        - '**/*Test.tsx'
        - '**/*Test.ts'
     plugins:
        - jest
     extends:
        - plugin:jest/recommended
rules:
   indent:
      - error
      - 3
      - SwitchCase: 1
   linebreak-style:
      - error
      - unix
   quotes:
      - error
      - single
   semi:
      - error
      - always
   no-unused-vars:
      - off
   '@typescript-eslint/no-unused-vars':
      - error
      - argsIgnorePattern: '^_'
        varsIgnorePattern: '^_'
        destructuredArrayIgnorePattern: '^_'
