# get help
default:
    just --list

# remove build data
clean:
    rm -rf ./dist

# clean and remove node_modules
purge: clean
    rm -rf ./node_modules

# format everything
fmt:
    npx prettier --write src/**/*.ts package.json tsconfig.json jest.config.js

# execute tests
test:
    npx jest

# build core
build:
    npx tsc

# mint a fancy new build of core
release: clean test build 

watch:
    npx chokidar "src/**/*.ts" -c "tsc"